### PR TITLE
Make lockfile on local disk

### PR DESCRIPTION
**Pull request by matyasselmeci**

### CODE REVIEW

**Comment by edquist** [comment]
What problem is this solving?

**Comment by matyasselmeci** [comment]
Random crashes due to AFS hiccups?

**Comment by edquist** [comment]
I'm worried that if there are AFS hiccups, it should still fail since all the repos etc are stored there.

I am also leery of using `/nobackup` - it seems like `/tmp` ought to do the trick.  But at least on `ingwe`, where this script runs, `/nobackup` currently does exist.

**Comment by matyasselmeci** [comment]
If there's an AFS problem (or any problem) fetching the repos, it will retry up to three times but it only tries to lock the lockfile once. (Maybe we should increase the retry count since we get SSL connect errors and HTTP transfer errors and whatnot...)

I'll move it to `/tmp`, that's always gonna exist.

**Pull request merged**
