### PR TITLE
Support new Jira statuses in status emailer

### PR DESCRIPTION
**Pull request by brianhlin**

### CODE REVIEW

**Comment by edquist** [comment]
It makes me shed a small tear of joy knowing that somehow this script still works

**Comment by brianhlin** [comment]
Thanks @edquist . Where does this actually run from and does the tool need to be manually updated there?

**Comment by edquist** [comment]
> Where does this actually run from and does the tool need to be manually updated there?

I had forgotten myself!

Apparently it runs as cndrutil@moria, which has a tools checkout under the homedir there.  I've gone ahead and updated it.  (Login has to be done via ksu)

**Comment by edquist** [comment]
test run sent the following email

```
Subject: JIRA ticket summary

JIRA Software tickets:

    * Open: 169 ()
    * Selected for Development: 3 ()
    * In Progress: 26 ()
    * Development Complete: 6 ()
    * Ready for Testing: 20 ()
    * Ready for Release: 2 ()

Completed at 2020-08-17 11:15
```

Seems to work.

**Pull request merged**
